# Generated by Django 4.2.3 on 2023-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summa',
            name='imag',
        ),
        migrations.AlterField(
            model_name='summa',
            name='txt',
            field=models.CharField(max_length=100),
        ),
    ]
