# Generated by Django 4.2.3 on 2023-07-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_alter_summa_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summa',
            old_name='txt',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='summa',
            name='imag',
        ),
        migrations.AddField(
            model_name='summa',
            name='dis',
            field=models.CharField(default='sfsdfs', max_length=250),
        ),
        migrations.AddField(
            model_name='summa',
            name='ima',
            field=models.ImageField(default='generator\\images\x0cull add.JPG', upload_to='generator/images/'),
        ),
    ]
